// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: encounter/encounter.proto

package encounter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiscEncounterCreateDto_EncounterStatus int32

const (
	MiscEncounterCreateDto_Active   MiscEncounterCreateDto_EncounterStatus = 0
	MiscEncounterCreateDto_Draft    MiscEncounterCreateDto_EncounterStatus = 1
	MiscEncounterCreateDto_Archived MiscEncounterCreateDto_EncounterStatus = 2
)

// Enum value maps for MiscEncounterCreateDto_EncounterStatus.
var (
	MiscEncounterCreateDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	MiscEncounterCreateDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x MiscEncounterCreateDto_EncounterStatus) Enum() *MiscEncounterCreateDto_EncounterStatus {
	p := new(MiscEncounterCreateDto_EncounterStatus)
	*p = x
	return p
}

func (x MiscEncounterCreateDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MiscEncounterCreateDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[0].Descriptor()
}

func (MiscEncounterCreateDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[0]
}

func (x MiscEncounterCreateDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MiscEncounterCreateDto_EncounterStatus.Descriptor instead.
func (MiscEncounterCreateDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{0, 0}
}

type MiscEncounterResponseDto_EncounterStatus int32

const (
	MiscEncounterResponseDto_Active   MiscEncounterResponseDto_EncounterStatus = 0
	MiscEncounterResponseDto_Draft    MiscEncounterResponseDto_EncounterStatus = 1
	MiscEncounterResponseDto_Archived MiscEncounterResponseDto_EncounterStatus = 2
)

// Enum value maps for MiscEncounterResponseDto_EncounterStatus.
var (
	MiscEncounterResponseDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	MiscEncounterResponseDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x MiscEncounterResponseDto_EncounterStatus) Enum() *MiscEncounterResponseDto_EncounterStatus {
	p := new(MiscEncounterResponseDto_EncounterStatus)
	*p = x
	return p
}

func (x MiscEncounterResponseDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MiscEncounterResponseDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[1].Descriptor()
}

func (MiscEncounterResponseDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[1]
}

func (x MiscEncounterResponseDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MiscEncounterResponseDto_EncounterStatus.Descriptor instead.
func (MiscEncounterResponseDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{1, 0}
}

type SocialEncounterCreateDto_EncounterStatus int32

const (
	SocialEncounterCreateDto_Active   SocialEncounterCreateDto_EncounterStatus = 0
	SocialEncounterCreateDto_Draft    SocialEncounterCreateDto_EncounterStatus = 1
	SocialEncounterCreateDto_Archived SocialEncounterCreateDto_EncounterStatus = 2
)

// Enum value maps for SocialEncounterCreateDto_EncounterStatus.
var (
	SocialEncounterCreateDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	SocialEncounterCreateDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x SocialEncounterCreateDto_EncounterStatus) Enum() *SocialEncounterCreateDto_EncounterStatus {
	p := new(SocialEncounterCreateDto_EncounterStatus)
	*p = x
	return p
}

func (x SocialEncounterCreateDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocialEncounterCreateDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[2].Descriptor()
}

func (SocialEncounterCreateDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[2]
}

func (x SocialEncounterCreateDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocialEncounterCreateDto_EncounterStatus.Descriptor instead.
func (SocialEncounterCreateDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{2, 0}
}

type EncounterResponseDto_EncounterStatus int32

const (
	EncounterResponseDto_Active   EncounterResponseDto_EncounterStatus = 0
	EncounterResponseDto_Draft    EncounterResponseDto_EncounterStatus = 1
	EncounterResponseDto_Archived EncounterResponseDto_EncounterStatus = 2
)

// Enum value maps for EncounterResponseDto_EncounterStatus.
var (
	EncounterResponseDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	EncounterResponseDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x EncounterResponseDto_EncounterStatus) Enum() *EncounterResponseDto_EncounterStatus {
	p := new(EncounterResponseDto_EncounterStatus)
	*p = x
	return p
}

func (x EncounterResponseDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterResponseDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[3].Descriptor()
}

func (EncounterResponseDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[3]
}

func (x EncounterResponseDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterResponseDto_EncounterStatus.Descriptor instead.
func (EncounterResponseDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{3, 0}
}

type EncounterResponseDto_EncounterType int32

const (
	EncounterResponseDto_Social   EncounterResponseDto_EncounterType = 0
	EncounterResponseDto_Hidden   EncounterResponseDto_EncounterType = 1
	EncounterResponseDto_Misc     EncounterResponseDto_EncounterType = 2
	EncounterResponseDto_Keypoint EncounterResponseDto_EncounterType = 3
)

// Enum value maps for EncounterResponseDto_EncounterType.
var (
	EncounterResponseDto_EncounterType_name = map[int32]string{
		0: "Social",
		1: "Hidden",
		2: "Misc",
		3: "Keypoint",
	}
	EncounterResponseDto_EncounterType_value = map[string]int32{
		"Social":   0,
		"Hidden":   1,
		"Misc":     2,
		"Keypoint": 3,
	}
)

func (x EncounterResponseDto_EncounterType) Enum() *EncounterResponseDto_EncounterType {
	p := new(EncounterResponseDto_EncounterType)
	*p = x
	return p
}

func (x EncounterResponseDto_EncounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterResponseDto_EncounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[4].Descriptor()
}

func (EncounterResponseDto_EncounterType) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[4]
}

func (x EncounterResponseDto_EncounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterResponseDto_EncounterType.Descriptor instead.
func (EncounterResponseDto_EncounterType) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{3, 1}
}

type HiddenLocationEncounterCreateDto_EncounterStatus int32

const (
	HiddenLocationEncounterCreateDto_Active   HiddenLocationEncounterCreateDto_EncounterStatus = 0
	HiddenLocationEncounterCreateDto_Draft    HiddenLocationEncounterCreateDto_EncounterStatus = 1
	HiddenLocationEncounterCreateDto_Archived HiddenLocationEncounterCreateDto_EncounterStatus = 2
)

// Enum value maps for HiddenLocationEncounterCreateDto_EncounterStatus.
var (
	HiddenLocationEncounterCreateDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	HiddenLocationEncounterCreateDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x HiddenLocationEncounterCreateDto_EncounterStatus) Enum() *HiddenLocationEncounterCreateDto_EncounterStatus {
	p := new(HiddenLocationEncounterCreateDto_EncounterStatus)
	*p = x
	return p
}

func (x HiddenLocationEncounterCreateDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HiddenLocationEncounterCreateDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[5].Descriptor()
}

func (HiddenLocationEncounterCreateDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[5]
}

func (x HiddenLocationEncounterCreateDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HiddenLocationEncounterCreateDto_EncounterStatus.Descriptor instead.
func (HiddenLocationEncounterCreateDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{4, 0}
}

type HiddenLocationEncounterResponseDto_EncounterStatus int32

const (
	HiddenLocationEncounterResponseDto_Active   HiddenLocationEncounterResponseDto_EncounterStatus = 0
	HiddenLocationEncounterResponseDto_Draft    HiddenLocationEncounterResponseDto_EncounterStatus = 1
	HiddenLocationEncounterResponseDto_Archived HiddenLocationEncounterResponseDto_EncounterStatus = 2
)

// Enum value maps for HiddenLocationEncounterResponseDto_EncounterStatus.
var (
	HiddenLocationEncounterResponseDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	HiddenLocationEncounterResponseDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x HiddenLocationEncounterResponseDto_EncounterStatus) Enum() *HiddenLocationEncounterResponseDto_EncounterStatus {
	p := new(HiddenLocationEncounterResponseDto_EncounterStatus)
	*p = x
	return p
}

func (x HiddenLocationEncounterResponseDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HiddenLocationEncounterResponseDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[6].Descriptor()
}

func (HiddenLocationEncounterResponseDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[6]
}

func (x HiddenLocationEncounterResponseDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HiddenLocationEncounterResponseDto_EncounterStatus.Descriptor instead.
func (HiddenLocationEncounterResponseDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{5, 0}
}

type EncounterInstanceResponseDto_EncounterInstanceStatus int32

const (
	EncounterInstanceResponseDto_Activated EncounterInstanceResponseDto_EncounterInstanceStatus = 0
	EncounterInstanceResponseDto_Completed EncounterInstanceResponseDto_EncounterInstanceStatus = 1
)

// Enum value maps for EncounterInstanceResponseDto_EncounterInstanceStatus.
var (
	EncounterInstanceResponseDto_EncounterInstanceStatus_name = map[int32]string{
		0: "Activated",
		1: "Completed",
	}
	EncounterInstanceResponseDto_EncounterInstanceStatus_value = map[string]int32{
		"Activated": 0,
		"Completed": 1,
	}
)

func (x EncounterInstanceResponseDto_EncounterInstanceStatus) Enum() *EncounterInstanceResponseDto_EncounterInstanceStatus {
	p := new(EncounterInstanceResponseDto_EncounterInstanceStatus)
	*p = x
	return p
}

func (x EncounterInstanceResponseDto_EncounterInstanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterInstanceResponseDto_EncounterInstanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[7].Descriptor()
}

func (EncounterInstanceResponseDto_EncounterInstanceStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[7]
}

func (x EncounterInstanceResponseDto_EncounterInstanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterInstanceResponseDto_EncounterInstanceStatus.Descriptor instead.
func (EncounterInstanceResponseDto_EncounterInstanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{9, 0}
}

type MiscEncounterCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChallengeDone bool                                   `protobuf:"varint,1,opt,name=ChallengeDone,proto3" json:"ChallengeDone,omitempty"`
	Title         string                                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture       string                                 `protobuf:"bytes,4,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude     float64                                `protobuf:"fixed64,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude      float64                                `protobuf:"fixed64,6,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius        float64                                `protobuf:"fixed64,7,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward      int32                                  `protobuf:"varint,8,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status        MiscEncounterCreateDto_EncounterStatus `protobuf:"varint,9,opt,name=Status,proto3,enum=MiscEncounterCreateDto_EncounterStatus" json:"Status,omitempty"`
}

func (x *MiscEncounterCreateDto) Reset() {
	*x = MiscEncounterCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiscEncounterCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiscEncounterCreateDto) ProtoMessage() {}

func (x *MiscEncounterCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiscEncounterCreateDto.ProtoReflect.Descriptor instead.
func (*MiscEncounterCreateDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{0}
}

func (x *MiscEncounterCreateDto) GetChallengeDone() bool {
	if x != nil {
		return x.ChallengeDone
	}
	return false
}

func (x *MiscEncounterCreateDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MiscEncounterCreateDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MiscEncounterCreateDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *MiscEncounterCreateDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetStatus() MiscEncounterCreateDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return MiscEncounterCreateDto_Active
}

type MiscEncounterResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64                                    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ChallengeDone bool                                     `protobuf:"varint,2,opt,name=ChallengeDone,proto3" json:"ChallengeDone,omitempty"`
	Title         string                                   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                                   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture       string                                   `protobuf:"bytes,5,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude     float64                                  `protobuf:"fixed64,6,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude      float64                                  `protobuf:"fixed64,7,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius        float64                                  `protobuf:"fixed64,8,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward      int32                                    `protobuf:"varint,9,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status        MiscEncounterResponseDto_EncounterStatus `protobuf:"varint,10,opt,name=Status,proto3,enum=MiscEncounterResponseDto_EncounterStatus" json:"Status,omitempty"`
}

func (x *MiscEncounterResponseDto) Reset() {
	*x = MiscEncounterResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiscEncounterResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiscEncounterResponseDto) ProtoMessage() {}

func (x *MiscEncounterResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiscEncounterResponseDto.ProtoReflect.Descriptor instead.
func (*MiscEncounterResponseDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{1}
}

func (x *MiscEncounterResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetChallengeDone() bool {
	if x != nil {
		return x.ChallengeDone
	}
	return false
}

func (x *MiscEncounterResponseDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MiscEncounterResponseDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MiscEncounterResponseDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *MiscEncounterResponseDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetStatus() MiscEncounterResponseDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return MiscEncounterResponseDto_Active
}

type SocialEncounterCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string                                   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description  string                                   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture      string                                   `protobuf:"bytes,3,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude    float64                                  `protobuf:"fixed64,4,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude     float64                                  `protobuf:"fixed64,5,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius       float64                                  `protobuf:"fixed64,6,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward     int32                                    `protobuf:"varint,7,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status       SocialEncounterCreateDto_EncounterStatus `protobuf:"varint,8,opt,name=Status,proto3,enum=SocialEncounterCreateDto_EncounterStatus" json:"Status,omitempty"`
	PeopleNumber int32                                    `protobuf:"varint,9,opt,name=PeopleNumber,proto3" json:"PeopleNumber,omitempty"`
}

func (x *SocialEncounterCreateDto) Reset() {
	*x = SocialEncounterCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialEncounterCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialEncounterCreateDto) ProtoMessage() {}

func (x *SocialEncounterCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialEncounterCreateDto.ProtoReflect.Descriptor instead.
func (*SocialEncounterCreateDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{2}
}

func (x *SocialEncounterCreateDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SocialEncounterCreateDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SocialEncounterCreateDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *SocialEncounterCreateDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SocialEncounterCreateDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SocialEncounterCreateDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *SocialEncounterCreateDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *SocialEncounterCreateDto) GetStatus() SocialEncounterCreateDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return SocialEncounterCreateDto_Active
}

func (x *SocialEncounterCreateDto) GetPeopleNumber() int32 {
	if x != nil {
		return x.PeopleNumber
	}
	return 0
}

type EncounterResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title       string                               `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string                               `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture     string                               `protobuf:"bytes,4,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude   float64                              `protobuf:"fixed64,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude    float64                              `protobuf:"fixed64,6,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius      float64                              `protobuf:"fixed64,7,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward    int32                                `protobuf:"varint,8,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status      EncounterResponseDto_EncounterStatus `protobuf:"varint,9,opt,name=Status,proto3,enum=EncounterResponseDto_EncounterStatus" json:"Status,omitempty"`
	Type        EncounterResponseDto_EncounterType   `protobuf:"varint,10,opt,name=Type,proto3,enum=EncounterResponseDto_EncounterType" json:"Type,omitempty"`
}

func (x *EncounterResponseDto) Reset() {
	*x = EncounterResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterResponseDto) ProtoMessage() {}

func (x *EncounterResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterResponseDto.ProtoReflect.Descriptor instead.
func (*EncounterResponseDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{3}
}

func (x *EncounterResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EncounterResponseDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EncounterResponseDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EncounterResponseDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *EncounterResponseDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EncounterResponseDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EncounterResponseDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *EncounterResponseDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *EncounterResponseDto) GetStatus() EncounterResponseDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return EncounterResponseDto_Active
}

func (x *EncounterResponseDto) GetType() EncounterResponseDto_EncounterType {
	if x != nil {
		return x.Type
	}
	return EncounterResponseDto_Social
}

type HiddenLocationEncounterCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PictureLongitude float64                                          `protobuf:"fixed64,1,opt,name=PictureLongitude,proto3" json:"PictureLongitude,omitempty"`
	PictureLatitude  float64                                          `protobuf:"fixed64,2,opt,name=PictureLatitude,proto3" json:"PictureLatitude,omitempty"`
	Title            string                                           `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Description      string                                           `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture          string                                           `protobuf:"bytes,5,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude        float64                                          `protobuf:"fixed64,6,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude         float64                                          `protobuf:"fixed64,7,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius           float64                                          `protobuf:"fixed64,8,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward         int32                                            `protobuf:"varint,9,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status           HiddenLocationEncounterCreateDto_EncounterStatus `protobuf:"varint,10,opt,name=Status,proto3,enum=HiddenLocationEncounterCreateDto_EncounterStatus" json:"Status,omitempty"`
}

func (x *HiddenLocationEncounterCreateDto) Reset() {
	*x = HiddenLocationEncounterCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiddenLocationEncounterCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenLocationEncounterCreateDto) ProtoMessage() {}

func (x *HiddenLocationEncounterCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenLocationEncounterCreateDto.ProtoReflect.Descriptor instead.
func (*HiddenLocationEncounterCreateDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{4}
}

func (x *HiddenLocationEncounterCreateDto) GetPictureLongitude() float64 {
	if x != nil {
		return x.PictureLongitude
	}
	return 0
}

func (x *HiddenLocationEncounterCreateDto) GetPictureLatitude() float64 {
	if x != nil {
		return x.PictureLatitude
	}
	return 0
}

func (x *HiddenLocationEncounterCreateDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HiddenLocationEncounterCreateDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HiddenLocationEncounterCreateDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *HiddenLocationEncounterCreateDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *HiddenLocationEncounterCreateDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *HiddenLocationEncounterCreateDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *HiddenLocationEncounterCreateDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *HiddenLocationEncounterCreateDto) GetStatus() HiddenLocationEncounterCreateDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return HiddenLocationEncounterCreateDto_Active
}

type HiddenLocationEncounterResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64                                              `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PictureLongitude float64                                            `protobuf:"fixed64,2,opt,name=PictureLongitude,proto3" json:"PictureLongitude,omitempty"`
	PictureLatitude  float64                                            `protobuf:"fixed64,3,opt,name=PictureLatitude,proto3" json:"PictureLatitude,omitempty"`
	Title            string                                             `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Description      string                                             `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture          string                                             `protobuf:"bytes,6,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude        float64                                            `protobuf:"fixed64,7,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude         float64                                            `protobuf:"fixed64,8,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius           float64                                            `protobuf:"fixed64,9,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward         int32                                              `protobuf:"varint,10,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status           HiddenLocationEncounterResponseDto_EncounterStatus `protobuf:"varint,11,opt,name=Status,proto3,enum=HiddenLocationEncounterResponseDto_EncounterStatus" json:"Status,omitempty"`
}

func (x *HiddenLocationEncounterResponseDto) Reset() {
	*x = HiddenLocationEncounterResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiddenLocationEncounterResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenLocationEncounterResponseDto) ProtoMessage() {}

func (x *HiddenLocationEncounterResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenLocationEncounterResponseDto.ProtoReflect.Descriptor instead.
func (*HiddenLocationEncounterResponseDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{5}
}

func (x *HiddenLocationEncounterResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetPictureLongitude() float64 {
	if x != nil {
		return x.PictureLongitude
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetPictureLatitude() float64 {
	if x != nil {
		return x.PictureLatitude
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HiddenLocationEncounterResponseDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HiddenLocationEncounterResponseDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *HiddenLocationEncounterResponseDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *HiddenLocationEncounterResponseDto) GetStatus() HiddenLocationEncounterResponseDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return HiddenLocationEncounterResponseDto_Active
}

type ListEncounterResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounters []*EncounterResponseDto `protobuf:"bytes,1,rep,name=encounters,proto3" json:"encounters,omitempty"`
}

func (x *ListEncounterResponseDto) Reset() {
	*x = ListEncounterResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEncounterResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEncounterResponseDto) ProtoMessage() {}

func (x *ListEncounterResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEncounterResponseDto.ProtoReflect.Descriptor instead.
func (*ListEncounterResponseDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{6}
}

func (x *ListEncounterResponseDto) GetEncounters() []*EncounterResponseDto {
	if x != nil {
		return x.Encounters
	}
	return nil
}

type UserPositionWithRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range     float64 `protobuf:"fixed64,1,opt,name=range,proto3" json:"range,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *UserPositionWithRange) Reset() {
	*x = UserPositionWithRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPositionWithRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPositionWithRange) ProtoMessage() {}

func (x *UserPositionWithRange) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPositionWithRange.ProtoReflect.Descriptor instead.
func (*UserPositionWithRange) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{7}
}

func (x *UserPositionWithRange) GetRange() float64 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *UserPositionWithRange) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UserPositionWithRange) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type EncounterInstanceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	EncounterId int64 `protobuf:"varint,2,opt,name=EncounterId,proto3" json:"EncounterId,omitempty"`
}

func (x *EncounterInstanceId) Reset() {
	*x = EncounterInstanceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterInstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterInstanceId) ProtoMessage() {}

func (x *EncounterInstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterInstanceId.ProtoReflect.Descriptor instead.
func (*EncounterInstanceId) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{8}
}

func (x *EncounterInstanceId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EncounterInstanceId) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

type EncounterInstanceResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           int64                                                `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Status           EncounterInstanceResponseDto_EncounterInstanceStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=EncounterInstanceResponseDto_EncounterInstanceStatus" json:"Status,omitempty"`
	CompletitionTime *timestamppb.Timestamp                               `protobuf:"bytes,3,opt,name=CompletitionTime,proto3" json:"CompletitionTime,omitempty"`
}

func (x *EncounterInstanceResponseDto) Reset() {
	*x = EncounterInstanceResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterInstanceResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterInstanceResponseDto) ProtoMessage() {}

func (x *EncounterInstanceResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterInstanceResponseDto.ProtoReflect.Descriptor instead.
func (*EncounterInstanceResponseDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{9}
}

func (x *EncounterInstanceResponseDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EncounterInstanceResponseDto) GetStatus() EncounterInstanceResponseDto_EncounterInstanceStatus {
	if x != nil {
		return x.Status
	}
	return EncounterInstanceResponseDto_Activated
}

func (x *EncounterInstanceResponseDto) GetCompletitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletitionTime
	}
	return nil
}

type TouristPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TouristId   int64   `protobuf:"varint,1,opt,name=TouristId,proto3" json:"TouristId,omitempty"`
	Longitude   float64 `protobuf:"fixed64,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude    float64 `protobuf:"fixed64,3,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	EncounterId int64   `protobuf:"varint,4,opt,name=EncounterId,proto3" json:"EncounterId,omitempty"`
}

func (x *TouristPosition) Reset() {
	*x = TouristPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouristPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouristPosition) ProtoMessage() {}

func (x *TouristPosition) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouristPosition.ProtoReflect.Descriptor instead.
func (*TouristPosition) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{10}
}

func (x *TouristPosition) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *TouristPosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TouristPosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TouristPosition) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

type TouristProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xp    int64 `protobuf:"varint,1,opt,name=Xp,proto3" json:"Xp,omitempty"`
	Level int64 `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
}

func (x *TouristProgress) Reset() {
	*x = TouristProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouristProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouristProgress) ProtoMessage() {}

func (x *TouristProgress) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouristProgress.ProtoReflect.Descriptor instead.
func (*TouristProgress) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{11}
}

func (x *TouristProgress) GetXp() int64 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *TouristProgress) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_encounter_encounter_proto protoreflect.FileDescriptor

var file_encounter_encounter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x02, 0x0a,
	0x16, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x3f, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e,
	0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36,
	0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x44, 0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x64, 0x10, 0x02, 0x22, 0x8b, 0x03, 0x0a, 0x18, 0x4d, 0x69, 0x73, 0x63, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x44, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x4d, 0x69, 0x73, 0x63,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x0f,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44,
	0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x64, 0x10, 0x02, 0x22, 0xf9, 0x02, 0x0a, 0x18, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52,
	0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x29, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x66, 0x74,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x10, 0x02,
	0x22, 0xd7, 0x03, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x36, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x10, 0x02, 0x22, 0x3f, 0x0a, 0x0d, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x69, 0x73, 0x63, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x03, 0x22, 0xbb, 0x03, 0x0a, 0x20, 0x48,
	0x69, 0x64, 0x64, 0x65, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12,
	0x2a, 0x0a, 0x10, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x58, 0x70, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x58, 0x70, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x49, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x36, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x10, 0x02, 0x22, 0xcf, 0x03, 0x0a, 0x22, 0x48, 0x69, 0x64,
	0x64, 0x65, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x10, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x58, 0x70, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x58, 0x70, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x4b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x36, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x10, 0x02, 0x22, 0x51, 0x0a, 0x18, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x35, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74,
	0x6f, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x67, 0x0a,
	0x15, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x86, 0x02, 0x0a, 0x1c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x4d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x46, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x37, 0x0a, 0x17, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x01, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x54, 0x6f, 0x75,
	0x72, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x54, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x54, 0x6f, 0x75, 0x72, 0x69, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x58, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x58, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x32,
	0x9a, 0x04, 0x0a, 0x09, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x4b, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x19, 0x2e,
	0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x15,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65,
	0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x23, 0x2e, 0x48, 0x69,
	0x64, 0x64, 0x65, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x4f, 0x66, 0x12, 0x16, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x19,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x15, 0x46,
	0x69, 0x6e, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x1d, 0x2e, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x08, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x69, 0x73,
	0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x15, 0x2e, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69,
	0x73, 0x63, 0x12, 0x14, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x69,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encounter_encounter_proto_rawDescOnce sync.Once
	file_encounter_encounter_proto_rawDescData = file_encounter_encounter_proto_rawDesc
)

func file_encounter_encounter_proto_rawDescGZIP() []byte {
	file_encounter_encounter_proto_rawDescOnce.Do(func() {
		file_encounter_encounter_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounter_encounter_proto_rawDescData)
	})
	return file_encounter_encounter_proto_rawDescData
}

var file_encounter_encounter_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_encounter_encounter_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_encounter_encounter_proto_goTypes = []interface{}{
	(MiscEncounterCreateDto_EncounterStatus)(0),               // 0: MiscEncounterCreateDto.EncounterStatus
	(MiscEncounterResponseDto_EncounterStatus)(0),             // 1: MiscEncounterResponseDto.EncounterStatus
	(SocialEncounterCreateDto_EncounterStatus)(0),             // 2: SocialEncounterCreateDto.EncounterStatus
	(EncounterResponseDto_EncounterStatus)(0),                 // 3: EncounterResponseDto.EncounterStatus
	(EncounterResponseDto_EncounterType)(0),                   // 4: EncounterResponseDto.EncounterType
	(HiddenLocationEncounterCreateDto_EncounterStatus)(0),     // 5: HiddenLocationEncounterCreateDto.EncounterStatus
	(HiddenLocationEncounterResponseDto_EncounterStatus)(0),   // 6: HiddenLocationEncounterResponseDto.EncounterStatus
	(EncounterInstanceResponseDto_EncounterInstanceStatus)(0), // 7: EncounterInstanceResponseDto.EncounterInstanceStatus
	(*MiscEncounterCreateDto)(nil),                            // 8: MiscEncounterCreateDto
	(*MiscEncounterResponseDto)(nil),                          // 9: MiscEncounterResponseDto
	(*SocialEncounterCreateDto)(nil),                          // 10: SocialEncounterCreateDto
	(*EncounterResponseDto)(nil),                              // 11: EncounterResponseDto
	(*HiddenLocationEncounterCreateDto)(nil),                  // 12: HiddenLocationEncounterCreateDto
	(*HiddenLocationEncounterResponseDto)(nil),                // 13: HiddenLocationEncounterResponseDto
	(*ListEncounterResponseDto)(nil),                          // 14: ListEncounterResponseDto
	(*UserPositionWithRange)(nil),                             // 15: UserPositionWithRange
	(*EncounterInstanceId)(nil),                               // 16: EncounterInstanceId
	(*EncounterInstanceResponseDto)(nil),                      // 17: EncounterInstanceResponseDto
	(*TouristPosition)(nil),                                   // 18: TouristPosition
	(*TouristProgress)(nil),                                   // 19: TouristProgress
	(*timestamppb.Timestamp)(nil),                             // 20: google.protobuf.Timestamp
}
var file_encounter_encounter_proto_depIdxs = []int32{
	0,  // 0: MiscEncounterCreateDto.Status:type_name -> MiscEncounterCreateDto.EncounterStatus
	1,  // 1: MiscEncounterResponseDto.Status:type_name -> MiscEncounterResponseDto.EncounterStatus
	2,  // 2: SocialEncounterCreateDto.Status:type_name -> SocialEncounterCreateDto.EncounterStatus
	3,  // 3: EncounterResponseDto.Status:type_name -> EncounterResponseDto.EncounterStatus
	4,  // 4: EncounterResponseDto.Type:type_name -> EncounterResponseDto.EncounterType
	5,  // 5: HiddenLocationEncounterCreateDto.Status:type_name -> HiddenLocationEncounterCreateDto.EncounterStatus
	6,  // 6: HiddenLocationEncounterResponseDto.Status:type_name -> HiddenLocationEncounterResponseDto.EncounterStatus
	11, // 7: ListEncounterResponseDto.encounters:type_name -> EncounterResponseDto
	7,  // 8: EncounterInstanceResponseDto.Status:type_name -> EncounterInstanceResponseDto.EncounterInstanceStatus
	20, // 9: EncounterInstanceResponseDto.CompletitionTime:type_name -> google.protobuf.Timestamp
	8,  // 10: Encounter.CreateMiscEncounter:input_type -> MiscEncounterCreateDto
	10, // 11: Encounter.CreateSocialEncounter:input_type -> SocialEncounterCreateDto
	12, // 12: Encounter.CreateHiddenLocationEncounter:input_type -> HiddenLocationEncounterCreateDto
	15, // 13: Encounter.FindAllInRangeOf:input_type -> UserPositionWithRange
	16, // 14: Encounter.FindEncounterInstance:input_type -> EncounterInstanceId
	18, // 15: Encounter.Activate:input_type -> TouristPosition
	16, // 16: Encounter.CompleteMisc:input_type -> EncounterInstanceId
	9,  // 17: Encounter.CreateMiscEncounter:output_type -> MiscEncounterResponseDto
	11, // 18: Encounter.CreateSocialEncounter:output_type -> EncounterResponseDto
	13, // 19: Encounter.CreateHiddenLocationEncounter:output_type -> HiddenLocationEncounterResponseDto
	14, // 20: Encounter.FindAllInRangeOf:output_type -> ListEncounterResponseDto
	17, // 21: Encounter.FindEncounterInstance:output_type -> EncounterInstanceResponseDto
	11, // 22: Encounter.Activate:output_type -> EncounterResponseDto
	19, // 23: Encounter.CompleteMisc:output_type -> TouristProgress
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_encounter_encounter_proto_init() }
func file_encounter_encounter_proto_init() {
	if File_encounter_encounter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounter_encounter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiscEncounterCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiscEncounterResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialEncounterCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiddenLocationEncounterCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiddenLocationEncounterResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEncounterResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPositionWithRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterInstanceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterInstanceResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouristPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouristProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounter_encounter_proto_rawDesc,
			NumEnums:      8,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encounter_encounter_proto_goTypes,
		DependencyIndexes: file_encounter_encounter_proto_depIdxs,
		EnumInfos:         file_encounter_encounter_proto_enumTypes,
		MessageInfos:      file_encounter_encounter_proto_msgTypes,
	}.Build()
	File_encounter_encounter_proto = out.File
	file_encounter_encounter_proto_rawDesc = nil
	file_encounter_encounter_proto_goTypes = nil
	file_encounter_encounter_proto_depIdxs = nil
}
