// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: encounter/encounter.proto

package encounter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiscEncounterCreateDto_EncounterStatus int32

const (
	MiscEncounterCreateDto_Active   MiscEncounterCreateDto_EncounterStatus = 0
	MiscEncounterCreateDto_Draft    MiscEncounterCreateDto_EncounterStatus = 1
	MiscEncounterCreateDto_Archived MiscEncounterCreateDto_EncounterStatus = 2
)

// Enum value maps for MiscEncounterCreateDto_EncounterStatus.
var (
	MiscEncounterCreateDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	MiscEncounterCreateDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x MiscEncounterCreateDto_EncounterStatus) Enum() *MiscEncounterCreateDto_EncounterStatus {
	p := new(MiscEncounterCreateDto_EncounterStatus)
	*p = x
	return p
}

func (x MiscEncounterCreateDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MiscEncounterCreateDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[0].Descriptor()
}

func (MiscEncounterCreateDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[0]
}

func (x MiscEncounterCreateDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MiscEncounterCreateDto_EncounterStatus.Descriptor instead.
func (MiscEncounterCreateDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{0, 0}
}

type MiscEncounterResponseDto_EncounterStatus int32

const (
	MiscEncounterResponseDto_Active   MiscEncounterResponseDto_EncounterStatus = 0
	MiscEncounterResponseDto_Draft    MiscEncounterResponseDto_EncounterStatus = 1
	MiscEncounterResponseDto_Archived MiscEncounterResponseDto_EncounterStatus = 2
)

// Enum value maps for MiscEncounterResponseDto_EncounterStatus.
var (
	MiscEncounterResponseDto_EncounterStatus_name = map[int32]string{
		0: "Active",
		1: "Draft",
		2: "Archived",
	}
	MiscEncounterResponseDto_EncounterStatus_value = map[string]int32{
		"Active":   0,
		"Draft":    1,
		"Archived": 2,
	}
)

func (x MiscEncounterResponseDto_EncounterStatus) Enum() *MiscEncounterResponseDto_EncounterStatus {
	p := new(MiscEncounterResponseDto_EncounterStatus)
	*p = x
	return p
}

func (x MiscEncounterResponseDto_EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MiscEncounterResponseDto_EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_encounter_proto_enumTypes[1].Descriptor()
}

func (MiscEncounterResponseDto_EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_encounter_proto_enumTypes[1]
}

func (x MiscEncounterResponseDto_EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MiscEncounterResponseDto_EncounterStatus.Descriptor instead.
func (MiscEncounterResponseDto_EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{1, 0}
}

type MiscEncounterCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChallengeDone bool                                   `protobuf:"varint,1,opt,name=ChallengeDone,proto3" json:"ChallengeDone,omitempty"`
	Title         string                                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture       string                                 `protobuf:"bytes,4,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude     float64                                `protobuf:"fixed64,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude      float64                                `protobuf:"fixed64,6,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius        float64                                `protobuf:"fixed64,7,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward      int32                                  `protobuf:"varint,8,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status        MiscEncounterCreateDto_EncounterStatus `protobuf:"varint,9,opt,name=Status,proto3,enum=MiscEncounterCreateDto_EncounterStatus" json:"Status,omitempty"`
}

func (x *MiscEncounterCreateDto) Reset() {
	*x = MiscEncounterCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiscEncounterCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiscEncounterCreateDto) ProtoMessage() {}

func (x *MiscEncounterCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiscEncounterCreateDto.ProtoReflect.Descriptor instead.
func (*MiscEncounterCreateDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{0}
}

func (x *MiscEncounterCreateDto) GetChallengeDone() bool {
	if x != nil {
		return x.ChallengeDone
	}
	return false
}

func (x *MiscEncounterCreateDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MiscEncounterCreateDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MiscEncounterCreateDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *MiscEncounterCreateDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *MiscEncounterCreateDto) GetStatus() MiscEncounterCreateDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return MiscEncounterCreateDto_Active
}

type MiscEncounterResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64                                    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ChallengeDone bool                                     `protobuf:"varint,2,opt,name=ChallengeDone,proto3" json:"ChallengeDone,omitempty"`
	Title         string                                   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                                   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Picture       string                                   `protobuf:"bytes,5,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Longitude     float64                                  `protobuf:"fixed64,6,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude      float64                                  `protobuf:"fixed64,7,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Radius        float64                                  `protobuf:"fixed64,8,opt,name=Radius,proto3" json:"Radius,omitempty"`
	XpReward      int32                                    `protobuf:"varint,9,opt,name=XpReward,proto3" json:"XpReward,omitempty"`
	Status        MiscEncounterResponseDto_EncounterStatus `protobuf:"varint,10,opt,name=Status,proto3,enum=MiscEncounterResponseDto_EncounterStatus" json:"Status,omitempty"`
}

func (x *MiscEncounterResponseDto) Reset() {
	*x = MiscEncounterResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_encounter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiscEncounterResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiscEncounterResponseDto) ProtoMessage() {}

func (x *MiscEncounterResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_encounter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiscEncounterResponseDto.ProtoReflect.Descriptor instead.
func (*MiscEncounterResponseDto) Descriptor() ([]byte, []int) {
	return file_encounter_encounter_proto_rawDescGZIP(), []int{1}
}

func (x *MiscEncounterResponseDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetChallengeDone() bool {
	if x != nil {
		return x.ChallengeDone
	}
	return false
}

func (x *MiscEncounterResponseDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MiscEncounterResponseDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MiscEncounterResponseDto) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *MiscEncounterResponseDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetXpReward() int32 {
	if x != nil {
		return x.XpReward
	}
	return 0
}

func (x *MiscEncounterResponseDto) GetStatus() MiscEncounterResponseDto_EncounterStatus {
	if x != nil {
		return x.Status
	}
	return MiscEncounterResponseDto_Active
}

var File_encounter_encounter_proto protoreflect.FileDescriptor

var file_encounter_encounter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x02, 0x0a, 0x16,
	0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x3f, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x4d,
	0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a,
	0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x44, 0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x64, 0x10, 0x02, 0x22, 0x8b, 0x03, 0x0a, 0x18, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x44,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x58, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x4d, 0x69, 0x73, 0x63, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x0f, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x72,
	0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x64, 0x10, 0x02, 0x32, 0x58, 0x0a, 0x09, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x12, 0x4b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f,
	0x1a, 0x19, 0x2e, 0x4d, 0x69, 0x73, 0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x11, 0x5a,
	0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encounter_encounter_proto_rawDescOnce sync.Once
	file_encounter_encounter_proto_rawDescData = file_encounter_encounter_proto_rawDesc
)

func file_encounter_encounter_proto_rawDescGZIP() []byte {
	file_encounter_encounter_proto_rawDescOnce.Do(func() {
		file_encounter_encounter_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounter_encounter_proto_rawDescData)
	})
	return file_encounter_encounter_proto_rawDescData
}

var file_encounter_encounter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_encounter_encounter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_encounter_encounter_proto_goTypes = []interface{}{
	(MiscEncounterCreateDto_EncounterStatus)(0),   // 0: MiscEncounterCreateDto.EncounterStatus
	(MiscEncounterResponseDto_EncounterStatus)(0), // 1: MiscEncounterResponseDto.EncounterStatus
	(*MiscEncounterCreateDto)(nil),                // 2: MiscEncounterCreateDto
	(*MiscEncounterResponseDto)(nil),              // 3: MiscEncounterResponseDto
}
var file_encounter_encounter_proto_depIdxs = []int32{
	0, // 0: MiscEncounterCreateDto.Status:type_name -> MiscEncounterCreateDto.EncounterStatus
	1, // 1: MiscEncounterResponseDto.Status:type_name -> MiscEncounterResponseDto.EncounterStatus
	2, // 2: Encounter.CreateMiscEncounter:input_type -> MiscEncounterCreateDto
	3, // 3: Encounter.CreateMiscEncounter:output_type -> MiscEncounterResponseDto
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_encounter_encounter_proto_init() }
func file_encounter_encounter_proto_init() {
	if File_encounter_encounter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounter_encounter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiscEncounterCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_encounter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiscEncounterResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounter_encounter_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encounter_encounter_proto_goTypes,
		DependencyIndexes: file_encounter_encounter_proto_depIdxs,
		EnumInfos:         file_encounter_encounter_proto_enumTypes,
		MessageInfos:      file_encounter_encounter_proto_msgTypes,
	}.Build()
	File_encounter_encounter_proto = out.File
	file_encounter_encounter_proto_rawDesc = nil
	file_encounter_encounter_proto_goTypes = nil
	file_encounter_encounter_proto_depIdxs = nil
}
