global:
  scrape_interval: 15s
rule_files:
   - "rules/recording_rules.yml"
scrape_configs:
  - job_name: 'myapp'
    static_configs:
      - targets: ['myapp:81']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
