x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: 172.21.0.8:24224

services:
  encounters:
    image: encounters
    restart: on-failure
    networks:
      - WebServerWithDB
      - monitoring
    logging: *fluent-bit
    ports:
      - "81:81"
    environment:
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      mongo:
        condition: service_healthy

# NoSQL: MongoDB
  mongo:
    image: mongo
    restart: always
    networks:
      - WebServerWithDB
      - monitoring
    logging: *fluent-bit
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

# NoSQL: Mongo Express
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo:27017/
    depends_on:
      - mongo
    logging: *fluent-bit
    ports:
      - "8081:8081"
    volumes:
      - mongo_express_data:/data/db

volumes:
  mongo_store:
  mongo_express_data:

networks:
  WebServerWithDB:
    name: WebServerWithDB
    driver: bridge
  monitoring:
    external: true
